# Generated by Django 4.0.3 on 2024-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
